version: "3.3"

services:
  traefik:
    image: traefik:v2.0
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/dynamic.yaml
      - --providers.docker.network=web
      - --providers.docker.network=secureweb
      - --entrypoints.web.address=:80
      - --entrypoints.web.address=:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/dev-disk-by-uuid-614b50f0-ff49-4f0d-b9e2-13fee156e08d/DATA/Servers/Configs/Traefik/dynamic.yaml:/dynamic.yaml
    networks:
      - web
      - secureweb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`monitor.ssnetworks.tk`)"
      - "traefik.http.routers.api.service=api@internal"

networks:
  web:
    external: true
  secureweb:
    external: true